### ISSUE TITLE
Review dos Requisitos

### ISSUE THREAD

**Issue by eduardolfalcao** [raphaelramosds/eimports#6]
Eimports (https://github.com/raphaelramosds/eimports)
 - Equipe: Poliana Ellen, Raphael Ramos, Niedson Fernando, Franklin Soares
 - Comentários:
	- Eu ainda não entendi muito bem o propósito do sistema. "Sistema de estoque de produtos. Nesse sistema o cliente é capaz de controlar suas compras de produtos e suas vendas para clientes, solicitadas via telefone ou Whatsapp."
	- Um vendedor vai usar o whatsapp para controlar o estoque e compras? O Whatsapp é a interface dele?
	- Usem a apresentação para "vender o produto" de vocês. Apresentem o objetivo e evidenciem porquê essa aplicação é importante.
	- Casos de uso
		- Lembrar do diagrama de casos de uso 
		- Autenticar usuário
			- 5a) o que seria um nome de usuário incorreto? 
			- autenticar no whatsapp?
		- Pesquisar produtos
			- quem é o autor? tem pré-condições?; omitiria 3a
	- Histórias de Usuário: OK

**Comment by raphaelramosds** [comment]
Modificações sugeridas foram implementadas
